project:
  type: website

website:
  title: "colab"
  reader-mode: true
  repo-url: https://github.com/coatless-quarto/stamp/
  repo-actions: [edit, issue]
  sidebar:
    logo: "TBA"
    logo-alt: "A hexagon logo for the colab extension."
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/coatless-quarto/stamp/
    contents: 
      - text: "Home"
        file: index.qmd
      - text: "Examples"
        file: qstamp-custom-placement.qmd
      - section: "Support"
        contents:
        - text: "FAQ"
          href: qstamp-faq.qmd
        - text: "Submit an issue"
          href: https://github.com/coatless-quarto/stamp/issues/new/choose
      - section: "Extra"
        contents:
        - qstamp-release-notes.qmd

format: 
  html:
    toc: true